[tool.poetry]
name = "paraphernalia"
version = "0.1.0"
description = "A collection of tools for making art"
authors = ["Joe Halliwell <joe.halliwell@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
moderngl = "^5.6.4"
moderngl-window = "^2.3.0"
click = "^7.1.2"
pyrr = "^0.10.3"
tqdm = "^4.59.0"
imageio = "^2.9.0"
imageio-ffmpeg = "^0.4.3"
torch = "^1.9.0"
torchvision = "^0.10.0"
xdg = "^5.1.0"
einops = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.8.0"
black = "^20.8b1"
ipykernel = "^5.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
render='paraphernalia.glsl:render'
preview='paraphernalia.glsl:preview'
