# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      # Setup OS
      #----------------------------------------------
      - name: Setup OpenGL
        run: |
          sudo apt-get update
          sudo apt-get install libegl1
      - name: Setup Libexmpi
        run: |
          sudo apt-get update
          sudo apt-get install libexempi8

      #----------------------------------------------
      # Check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #----------------------------------------------
      # Setup python
      #----------------------------------------------
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      #----------------------------------------------
      # Install uv and get it setup
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.8.17"

      #----------------------------------------------
      # Install the project
      #----------------------------------------------
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      #----------------------------------------------
      # Lint
      #----------------------------------------------
      - name: Lint with ruff
        uses: jpetrucciani/ruff-check@main

      #----------------------------------------------
      # Run test suite
      #----------------------------------------------
      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
